version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: formationMayenneAdmin
      MONGO_INITDB_ROOT_PASSWORD: 12345
    networks:
      - mongo_network

volumes:
  mongodb_data:
    driver: local

networks:
  mongo_network:
    driver: bridge
